[package]
name        = "rc-rpc"
description = "JSON-RPC 2.0 API server and client"

version.workspace     = true
edition.workspace     = true
rust-version.workspace = true
authors.workspace     = true
license.workspace     = true
repository.workspace  = true

[dependencies]
rc-primitives = { workspace = true }
rc-storage    = { workspace = true }
rc-mempool    = { workspace = true }

axum          = { workspace = true }
tower         = { workspace = true }
tower-http    = { workspace = true }
jsonrpsee     = { workspace = true }
serde         = { workspace = true }
serde_json    = { workspace = true }
thiserror     = { workspace = true }
tracing       = { workspace = true }
tokio         = { workspace = true }
hex           = { workspace = true }